on:
  repository_dispatch:
    types:
    - release
    
env:
  NEW_RELEASE_NAME: TestName
  NEW_RELEASE_BODY: TestBody
  NEW_RELEASE_ID: 1
  NEW_RELEASE_TAG_NAME: v0
  NEW_ASSET_ID: 1
  
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Request Release
        id: requestRelease
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Bridge/releases/latest -o release.json
      - name: JSON to Variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'release.json'
          prefix: release
      - name: List Assets
        id: listAssets
        env:
          NEW_RELEASE_ID: "${{env.release_id}}"
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Bridge/releases/${{env.NEW_RELEASE_ID}}/assets
      - name: Download Release Assets
        id: downloadAssets
        env:
          NEW_RELEASE_TAG_NAME: "${{env.release_tag_name}}"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Pirate-MIDI/Bridge'
          version: 'tags/${{env.NEW_RELEASE_TAG_NAME}}'
          file: ""
          regex: true
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Echo Downloaded Assets
        run: ls
      - name: Create Mirror Release
        id: createRelease
        env:
          NEW_RELEASE_NAME: "${{env.release_name}}"
          NEW_RELEASE_BODY: "${{toJson(env.release_body)}}"
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking/releases \
          -d '{"tag_name":"v0.0.1","target_commitish":"main","name":"${{env.NEW_RELEASE_NAME}}","body":${{env.NEW_RELEASE_BODY}},"draft":false,"prerelease":false,"generate_release_notes":false}' 
      
      - name: Upload Release Asset
        id: uploadReleaseAsset 
        uses: AButler/upload-release-assets@v2.0
        with:
          files: './bridge6_v1_0_3_1.bin'
          repo-token: ${{ secrets.RELEASE_TOKEN }}
          release-tag: 'v0.0.1'
        
