on:
  repository_dispatch:
    types:
    - release
jobs:
  my-job:
    env:
      NEW_RELEASE_NAME: none
    runs-on: ubuntu-latest
    steps:
      - name: Enable Echo
        run: |
          ::echo::on
      - name: Request Release
        id: myRequest
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Bridge/releases/latest 
      - name: Echo Variables
        env:
          NEW_RELEASE_NAME: ${{ steps.myRequest.outputs.response.name }}
        run: |
          echo "${{ NEW_RELEASE_NAME }}"
      - name: Create Mirror Release
        id: createRelease
        env:
          NEW_RELEASE_NAME: ${{ steps.myRequest.outputs.response.name }}
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking/releases \
          -d '{"tag_name":"v0.0.1","target_commitish":"main","name":"'"${NEW_RELEASE_NAME}"'","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'

