on:
  repository_dispatch:
    types:
    - release
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
