on:
  repository_dispatch:
    types:
    - release
    
env:
  NEW_RELEASE_NAME: TestName
  NEW_RELEASE_BODY: TestBody
  NEW_RELEASE_TAG_NAME: v0
  
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Request Release
        id: myRequest
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Bridge/releases/latest -o release.json
        
      - name: JSON to Variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'release.json'
          prefix: release
      - name: Echo Variables
        env:
          NEW_RELEASE_NAME: "${{env.release_name}}"
        run: echo $NEW_RELEASE_NAME
        
      - name: Create Mirror Release
        id: createRelease
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking/releases \
          -d '{"tag_name":"v0.0.1","target_commitish":"main","name":"{{$NEW_RELEASE_NAME}}","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'

