on:
  repository_dispatch:
    types:
    - release
    
env:
  NEW_RELEASE_NAME: TestName
  NEW_RELEASE_BODY: TestBody
  NEW_RELEASE_ID: 1
  NEW_RELEASE_TAG_NAME: v0
  NEW_ASSET_ID: 1
  
jobs:
  publishRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Request All Releases
        id: requestAllReleases
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Bridge/releases -o release.json
          
      - name: JSON to Variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'release.json'
          prefix: release
          
      - name: Create New Assets Folder
        run: mkdir ./assets
        
      - name: Download Release Assets
        if: contains(env.release_0_name, 'alpha') != true
        id: downloadAssets
        env:
          NEW_RELEASE_TAG_NAME: "${{env.release_0_tag_name}}"
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Pirate-MIDI/Bridge'
          version: 'tags/${{env.NEW_RELEASE_TAG_NAME}}'
          file: "bridge"
          regex: true
          target: 'assets/'
          token: ${{ secrets.RELEASE_TOKEN }}
          
      - name: Echo Downloaded Assets
        run: ls assets
        
      - name: Create Mirror Release
        if: contains(env.release_0_name, 'alpha') != true
        id: createRelease
        env:
          NEW_RELEASE_NAME: "${{env.release_0_name}}"
          NEW_RELEASE_BODY: "${{toJson(env.release_0_body)}}"
          NEW_RELEASE_TAG_NAME: "${{env.release_0_tag_name}}"
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
          https://api.github.com/repos/Pirate-MIDI/Pirate-MIDI-Features-Bug-Tracking/releases \
          -d '{"tag_name":"${{env.NEW_RELEASE_TAG_NAME}}","target_commitish":"main","name":"${{env.NEW_RELEASE_NAME}}","body":${{env.NEW_RELEASE_BODY}},"draft":false,"prerelease":false,"generate_release_notes":false}' 
      
      - name: Upload Release Asset
        if: contains(env.release_0_name, 'alpha') != true
        id: uploadReleaseAsset
        env:
          NEW_RELEASE_TAG: "${{env.release_0_tag_name}}"
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'assets/*.bin'
          repo-token: ${{ secrets.RELEASE_TOKEN }}
          release-tag: '${{env.NEW_RELEASE_TAG}}'
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
      
      - name: Post Alpha Announcement
        id: slackAlpha
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C03HC5W3M7F'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
